export const Routes = {
  // Splash
  Splash: '/index',

  // Auth
  AuthLogin: '/(auth)/login',
  AuthRegister: '/(auth)/register',
  AuthForgotPassword: '/(auth)/forgot-password',
  AuthVerifyEmail: '/(auth)/verify-email',

  // Admin Area
  AdminDashboard: '/(admin)/dashboard',
  AdminAddProduct: '/(admin)/(products)/add-product',
  AdminProducts: '/(admin)/(products)/index',
  AdminInventory: '/(admin)/(products)/inventory',
  AdminEditProduct: '/(admin)/(products)/edit-product/',
  AdminProductVariants: '/(admin)/(products)/variants',
  AdminOrders: '/(admin)/(orders)/index',
  AdminOrderDetail: '/(admin)/(orders)/detail/',
  AdminMore: '/(admin)/(more)/index',
  AdminCoupons: '/(admin)/(more)/coupons',
  AdminAddCoupon: '/(admin)/(more)/add-coupon',
  AdminCategories: '/(admin)/(more)/categories',
  AdminCustomers: '/(admin)/(more)/customers',
  AdminReports: '/(admin)/(more)/reports',
  AdminReviews: '/(admin)/(more)/reviews',
  AdminEditCoupon: '/(admin)/(more)/edit-coupon/',
  AdminRespondReview: '/(admin)/(more)/respond-review/',
  AdminProfile: '/(admin)/(more)/profile',
  AdminEditProfile: '/(admin)/(more)/profile/edit-profile',
  AdminChangePassword: '/(admin)/(more)/profile/change-password',
  AdminReferral: '/(admin)/(more)/profile/referral',
  AdminSettings: '/(admin)/(more)/profile/settings',

  // Customer Area
  CustomerHome: '/(customer)/(home)',
  CustomerNotifications: '/(customer)/(home)/notifications',
  CustomerSearch: '/(customer)/(home)/search',
  CustomerProductDetail: '/(customer)/(home)/product/',
  // CustomerProductReviewDetail: '/(customer)/(home)/product/:id/reviews/',
  CustomerCategories: '/(customer)/(categories)/index',
  CustomerCategoryDetail: '/(customer)/(categories)/:categoryId',
  CustomerSubCategoryDetail: '/(customer)/(categories)/subcategory/',
  CustomerCart: '/(customer)/(cart)/index',
  CustomerApplyCoupon: '/(customer)/(cart)/apply-coupon',
  CustomerCheckout: '/(customer)/(cart)/checkout',
  CustomerOrderSuccess: '/(customer)/(cart)/order-success',
  CustomerPaymentMethod: '/(customer)/(cart)/payment-method',
  CustomerSelectAddress: '/(customer)/(cart)/select-address',
  CustomerWishlist: '/(customer)/wishlist',
  CustomerProfile: '/(customer)/(profile)/index',
  CustomerEditProfile: '/(customer)/(profile)/edit-profile',
  CustomerAddAddress: '/(customer)/(profile)/add-address',
  CustomerAddressBook: '/(customer)/(profile)/address-book',
  CustomerChangePassword: '/(customer)/(profile)/change-password',
  CustomerOrders: '/(customer)/(profile)/orders',
  CustomerOrderDetail: '/(customer)/(profile)/order-detail/',
  // CustomerWriteReview: '/(customer)/(profile)/order-detail/:id/write-review',
  CustomerOrderTracking: '/(customer)/(profile)/tracking/',
  CustomerReferral: '/(customer)/(profile)/referral',
  CustomerSettings: '/(customer)/(profile)/settings',
  CustomerLoyaltyPoints: '/(customer)/(profile)/loyalty-points',

  // Super Area
  SuperDashboard: '/(super)/dashboard',
  SuperAddProduct: '/(super)/(products)/add-product',
  SuperProducts: '/(super)/(products)/index',
  SuperInventory: '/(super)/(products)/inventory',
  SuperEditProduct: '/(super)/(products)/edit-product/',
  SuperProductVariants: '/(super)/(products)/variants/:productId',
  SuperOrders: '/(super)/(orders)/index',
  SuperOrderDetail: '/(super)/(orders)/detail/',
  SuperMore: '/(super)/(more)/index',
  SuperCoupons: '/(super)/(more)/coupons',
  SuperAddCoupon: '/(super)/(more)/add-coupon',
  SuperCategories: '/(super)/(more)/categories',
  SuperCustomers: '/(super)/(more)/customers',
  SuperReports: '/(super)/(more)/reports',
  SuperReviews: '/(super)/(more)/reviews',
  SuperEditCoupon: '/(super)/(more)/edit-coupon/',
  SuperRespondReview: '/(super)/(more)/respond-review/',
  SuperProfile: '/(super)/(more)/profile/',
  SuperEditProfile: '/(super)/(more)/profile/edit-profile',
  SuperChangePassword: '/(super)/(more)/profile/change-password',
  SuperReferral: '/(super)/(more)/profile/referral',
  SuperSettings: '/(super)/(more)/profile/settings',
  SuperStaffs: '/(super)/(staffs)/index',
  SuperAddStaff: '/(super)/(staffs)/add-staff',
  SuperEditStaff: '/(super)/(staffs)/edit-staff/',
} as const;