// Routes map (string type to allow appending ids like `/.../edit/` + id)
export const Routes: Record<string, string> = {
  // Splash
  Splash: '/',

  // Auth
  AuthLogin: '/(auth)/login',
  AuthRegister: '/(auth)/register',
  AuthForgotPassword: '/(auth)/forgot-password',
  AuthVerifyEmail: '/(auth)/verify-email',

  // Admin Area
  AdminDashboard: '/(role)/(admin)/dashboard',
  AdminAddProduct: '/(role)/(admin)/(products)/add-product',
  AdminProducts: '/(role)/(admin)/(products)',
  AdminInventory: '/(role)/(admin)/(products)/inventory',
  AdminEditProduct: '/(role)/(admin)/(products)/edit-product/',
  AdminProductVariants: '/(role)/(admin)/(products)/variants/',
  AdminOrders: '/(role)/(admin)/(orders)/',
  AdminOrderDetail: '/(role)/(admin)/(orders)/detail/',
  AdminMore: '/(role)/(admin)/(more)/',
  AdminCoupons: '/(role)/(admin)/(more)/coupons',
  AdminAddCoupon: '/(role)/(admin)/(more)/add-coupon',
  AdminCategories: '/(role)/(admin)/(more)/categories',
  AdminCustomers: '/(role)/(admin)/(more)/customers',
  AdminReports: '/(role)/(admin)/(more)/reports',
  AdminReviews: '/(role)/(admin)/(more)/reviews',
  AdminEditCoupon: '/(role)/(admin)/(more)/edit-coupon/',
  AdminRespondReview: '/(role)/(admin)/(more)/respond-review/',
  AdminProfile: '/(role)/(admin)/(more)/profile',
  AdminEditProfile: '/(role)/(admin)/(more)/profile/edit-profile',
  AdminChangePassword: '/(role)/(admin)/(more)/profile/change-password',
  AdminReferral: '/(role)/(admin)/(more)/profile/referral',
  AdminSettings: '/(role)/(admin)/(more)/profile/settings',


  // Customer Area
  CustomerHome: '/(role)/(customer)/(home)',
  CustomerNotifications: '/(role)/(customer)/(home)/notifications',
  CustomerSearch: '/(role)/(customer)/(home)/search',
  CustomerProductDetail: '/(role)/(customer)/(home)/product/',
  // CustomerProductReviewDetail: '/(role)/(customer)/(home)/product/:id/reviews/',
  CustomerCategories: '/(role)/(customer)/(categories)/',
  CustomerCategoryDetail: '/(role)/(customer)/(categories)/',
  CustomerSubCategoryDetail: '/(role)/(customer)/(categories)/subcategory/',
  CustomerCart: '/(role)/(customer)/(cart)/',
  CustomerApplyCoupon: '/(role)/(customer)/(cart)/apply-coupon',
  CustomerCheckout: '/(role)/(customer)/(cart)/checkout',
  CustomerOrderSuccess: '/(role)/(customer)/(cart)/order-success',
  CustomerPaymentMethod: '/(role)/(customer)/(cart)/payment-method',
  CustomerSelectAddress: '/(role)/(customer)/(cart)/select-address',
  CustomerWishlist: '/(role)/(customer)/wishlist',
  CustomerProfile: '/(role)/(customer)/(profile)/',
  CustomerEditProfile: '/(role)/(customer)/(profile)/edit-profile',
  CustomerAddAddress: '/(role)/(customer)/(profile)/add-address',
  CustomerAddressBook: '/(role)/(customer)/(profile)/address-book',
  CustomerChangePassword: '/(role)/(customer)/(profile)/change-password',
  CustomerOrders: '/(role)/(customer)/(profile)/orders',
  CustomerOrderDetail: '/(role)/(customer)/(profile)/order-detail/',
  // CustomerWriteReview: '/(role)/(customer)/(profile)/order-detail/:id/write-review',
  CustomerOrderTracking: '/(role)/(customer)/(profile)/tracking/',
  CustomerCoupon: '/(role)/(customer)/(profile)/coupon',
  CustomerSettings: '/(role)/(customer)/(profile)/settings',
  CustomerLoyaltyPoints: '/(role)/(customer)/(profile)/loyalty-points',
  CustomerEditAddress: '/(role)/(customer)/(profile)/edit-address',
  CustomerWriteReview: '/(customer)/(profile)/order-detail/:id/write-review',




  // Super Area
  SuperDashboard: '/(role)/(super)/dashboard',
  SuperAddProduct: '/(role)/(super)/(products)/add-product',
  SuperProducts: '/(role)/(super)/(products)/',
  SuperInventory: '/(role)/(super)/(products)/inventory',
  SuperEditProduct: '/(role)/(super)/(products)/edit-product/',
  SuperProductVariants: '/(role)/(super)/(products)/variants/',
  SuperOrders: '/(role)/(super)/(orders)/',
  SuperOrderDetail: '/(role)/(super)/(orders)/detail/',
  SuperMore: '/(role)/(super)/(more)/',
  SuperCoupons: '/(role)/(super)/(more)/coupons',
  SuperAddCoupon: '/(role)/(super)/(more)/add-coupon',
  SuperCategories: '/(role)/(super)/(more)/categories',
  SuperCustomers: '/(role)/(super)/(more)/customers',
  SuperReports: '/(role)/(super)/(more)/reports',
  SuperReviews: '/(role)/(super)/(more)/reviews',
  SuperEditCoupon: '/(role)/(super)/(more)/edit-coupon/',
  SuperRespondReview: '/(role)/(super)/(more)/respond-review/',
  SuperProfile: '/(role)/(super)/(more)/profile/',
  SuperEditProfile: '/(role)/(super)/(more)/profile/edit-profile',
  SuperChangePassword: '/(role)/(super)/(more)/profile/change-password',
  SuperReferral: '/(role)/(super)/(more)/profile/referral',
  SuperSettings: '/(role)/(super)/(more)/profile/settings',
  SuperStaffs: '/(role)/(super)/(staffs)/',
  SuperAddStaff: '/(role)/(super)/(staffs)/add-staff',
  SuperEditStaff: '/(role)/(super)/(staffs)/edit-staff/',
} as const;